<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="paises.css"?>

<!DOCTYPE pais [
    <!ELEMENT paises (pais+)>
    <!ELEMENT pais (nombre, continente, localizacion, estados?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descipcion (#PCDATA)>
    <!ATTLIST pais continente CDATA #REQUIRED>
]>

<paises>
    <pais continente="Europa">
        <nombre> Italia </nombre>
        <descipcion> Italia es un país ubicado en Europa occidental y miembro de la Unión Europea. Su territorio se extiende por el sur de Europa, en islas del mar Mediterráneo (como Sicilia y Cerdeña) y en las islas Pelagias (que pertenecen al continente africano). </descipcion>
    </pais>
    <pais continente="Asia">
        <nombre> China </nombre>
        <descipcion> China es el país más poblado del mundo y la segunda potencia económica mundial. La República Popular China, o en chino “中华人民共和国” (Zhōnghuá Rénmín Gònghéguó), es un Estado unipartidista, gobernado por el Partido Comunista y tiene la sede de su gobierno en la capital, Beijing. </descipcion>
    </pais>
    <pais continente="Africa">
        <nombre> Marruecos </nombre>
        <descipcion>El Reino de Marruecos se sitúa en el extremo Noroeste del continente africano entre 21º y 36º de latitud Norte. Sólo 20 Km lo separa de Europa, por medio del Estrecho de Gibraltar. Su superficie es de 446.550 Km2, y 71.850 Km2 si se incluye el territorio del Sahara Occidental bajo el control de Rabat.</descipcion>
    </pais>
    <pais continente="Europa">
        <nombre> España </nombre>
        <descipcion>España o Reino de España es un país situado en el sur de Europa occidental y norte de África, que está compuesto por comunidades autónomas y es miembro de la Unión Europea. La capital de España es la ciudad de Madrid y es un país gobernado por una monarquía parlamentaria bajo una forma de gobierno democrática.</descipcion>
    </pais>
    <pais continente="America">
        <nombre> Mexico </nombre>
        <descipcion>Es el décimo cuarto país más extenso del mundo, con una superficie cercana a los 2 millones de kilómetros cuadrados. Es el undécimo país más poblado del mundo, con una población de aproximadamente 118 millones de habitantes. La lengua materna es el español, que convive junto con 67 lenguas indígenas.</descipcion>
    </pais>
    <pais continente="Africa">
        <nombre> Egipto </nombre>
        <descipcion>Egipto se encuentra en el extremo noreste del continente africano, posee costas sobre el mar Mediterráneo y el mar Rojo. Limita al oeste con Libia, al sur con Sudán, al norte con el Mediterráneo y al este con el mar Rojo e Israel.</descipcion>
    </pais>
    <pais continente="Asia">
        <nombre> Japón </nombre>
        <descipcion>Japón es un país insular que se extiende a lo largo de la costa Pacífica del nordeste de Asia. La isla principal es Honshu, y las otras tres más grandes son Hokkaido, en el norte del país, y Shikoku y Kyushu en el sur. Más de 4.000 pequeñas islas rodean a estas cuatro principales.</descipcion>
    </pais>
    <pais continente="America">
        <nombre> USA </nombre>
        <descipcion>EE. UU. está compuesto por 50 estados y tiene una superficie total de 9.629,101 kilómetros cuadrados, lo que lo convierte en el tercer estado más grande del mundo. Al este del continente americano se encuentra el océano Atlántico y al oeste el océano Pacífico.</descipcion>
    </pais>
    <pais continente="Europa">
        <nombre> Polonia </nombre>
        <descipcion>La República de Polonia está situada en Europa central; al oeste es fronteriza con Alemania, al sur con la República Checa y Eslovaquia, y al este con Lituania y Ucrania, mientras que su frontera septentrional está delimitada por el mar Báltico y Rusia (el enclave de Kaliningrado).</descipcion>
    </pais>
    <pais continente="Asia">
        <nombre> Singapur </nombre>
        <descipcion>Singapur es un pequeño país muy urbanizado del Sureste de Asia, ubicado en el extremo sur de la península malaya; se sitúa entre Malasia con la que limita al norte, e Indonesia, al sur. La superficie total de Singapur es de 721,5 kilómetros cuadrados, con 193 km de costas.</descipcion>
    </pais>
</paises>
